name: Fabriquer l'APK Automatiquement

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Récupération de ton code
      uses: actions/checkout@v4

    - name: 2. Installation de Java (Le moteur Android)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 3. Détection et Compilation de l'APK
      run: |
        # Le robot cherche le fichier gradlew dans tous les sous-dossiers
        GRADLEW_PATH=$(find . -name "gradlew" -print -quit)
        
        if [ -z "$GRADLEW_PATH" ]; then
          echo "❌ Erreur : Impossible de trouver le fichier 'gradlew' dans tes dossiers."
          exit 1
        fi
        
        # On extrait le chemin du dossier qui contient gradlew
        DOSSIER_PROJET=$(dirname "$GRADLEW_PATH")
        echo "🟢 Projet Android détecté dans : $DOSSIER_PROJET"
        
        # On se déplace dans ce dossier pour lancer la cuisine
        cd "$DOSSIER_PROJET"
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: 4. Mise à disposition du fichier APK
      uses: actions/upload-artifact@v4
      with:
        name: Mon_Application_Android_APK
        path: "**/build/outputs/apk/debug/app-debug.apk" # Cherche l'APK partout
